## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file subgroupOfRealNumbers.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_65 = Integer(65); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_254 = Integer(254); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_243 = Integer(243); _sage_const_269 = Integer(269); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11); _sage_const_0 = Integer(0); _sage_const_228 = Integer(228); _sage_const_15 = Integer(15); _sage_const_239 = Integer(239); _sage_const_258 = Integer(258); _sage_const_223 = Integer(223)## This file (subgroupOfRealNumbers.sagetex.sage) was *autogenerated* from subgroupOfRealNumbers.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('subgroupOfRealNumbers', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_65 
_st_.blockbegin()
try:
 # THIS code generates a random Real Number. Options:
 # Natural
 # Whole
 # Integer
 # Rational
 # Irrational
 # Not a Real number
 # Complex
 # Dividing by zero
 
 def generateNatural():
     denominator = ZZ.random_element(_sage_const_15 )+_sage_const_1 
     numerator = denominator*(ZZ.random_element(_sage_const_15 )+_sage_const_1 )
     negOrNo = ""
     displayProblem = [numerator**_sage_const_2 , denominator**_sage_const_2 , negOrNo]
     return displayProblem
 
 def generateWhole():
     denomBefore = ZZ.random_element(_sage_const_15 )+_sage_const_1 
     numerator = _sage_const_0 
     negOrNo = ""
     maybeComplexDisplayed = sample(["Complex", "Nah"], _sage_const_1 )
     if maybeComplexDisplayed == "Complex":
         denominator = latex(denomBefore*pi)
     else:
         denominator = denomBefore
     displayProblem = [numerator**_sage_const_2 , denominator**_sage_const_2 , negOrNo]
     return displayProblem
 
 def generateInteger():
     denominator = ZZ.random_element(_sage_const_15 )+_sage_const_1 
     numerator = denominator*(ZZ.random_element(_sage_const_15 )+_sage_const_1 )
     negOrNo = "-"
     displayProblem = [numerator**_sage_const_2 , denominator**_sage_const_2 , negOrNo]
     return displayProblem
 
 def generateRational():
     numeratorBefore = ZZ.random_element(_sage_const_15 )+_sage_const_7 
     denominatorBefore = ZZ.random_element(_sage_const_15 )+_sage_const_7 
     negative = ZZ.random_element(_sage_const_2 )
     if negative == _sage_const_0 :
         negOrNo = ""
     else:
         negOrNo = "-"
     counter = _sage_const_0 
     while gcd(numeratorBefore, denominatorBefore) >= min(numeratorBefore, denominatorBefore):
         numerator = ZZ.random_element(_sage_const_15 )+_sage_const_7 
         denominator = ZZ.random_element(_sage_const_15 )+_sage_const_7 
         counter = counter + _sage_const_1 
         print "Numerator: %d, \n Denominator: %d, \n Counter: %d" %(numerator, denominator, counter)
     numerator = numeratorBefore**_sage_const_2 
     denominator = denominatorBefore**_sage_const_2 
     displayProblem = [numerator, denominator, negOrNo]
     return displayProblem
 
 def generateIrrational():
     numeratorBefore = ZZ.random_element(_sage_const_15 )+_sage_const_1 
     denominatorBefore = ZZ.random_element(_sage_const_15 )+_sage_const_1 
     negative = ZZ.random_element(_sage_const_2 )
     if negative == _sage_const_0 :
         negOrNo = ""
     else:
         negOrNo = "-"
     integerType = type(sqrt(_sage_const_4 ))
     while type(sqrt(numeratorBefore/denominatorBefore)) == integerType:
         numeratorBefore = ZZ.random_element(_sage_const_15 )+_sage_const_1 
         denominatorBefore = ZZ.random_element(_sage_const_15 )+_sage_const_1 
     numerator = numeratorBefore
     denominator = denominatorBefore
     displayProblem = [numerator, denominator, negOrNo]
     return displayProblem
 
 def generateNotReal():
     numeratorBefore = ZZ.random_element(_sage_const_15 )+_sage_const_1 
     denominatorBefore = ZZ.random_element(_sage_const_15 )+_sage_const_1 
     negative = ZZ.random_element(_sage_const_2 )
     if negative == _sage_const_0 :
         negOrNo = ""
     else:
         negOrNo = "-"
     complexOrNotNumber = sample(["ComplexTop", "ComplexBottom", "NotNumber"], _sage_const_1 )[_sage_const_0 ]
     if complexOrNotNumber=="ComplexTop":
         numerator = -numeratorBefore*pi
         denominator = denominatorBefore
     elif complexOrNotNumber=="ComplexBottom":
         numerator = -numeratorBefore
         denominator = denominatorBefore*pi
     elif complexOrNotNumber=="NotNumber":
         topOrBottom = ZZ.random_element(_sage_const_2 )
         if topOrBottom==_sage_const_0 :
             numerator = -numeratorBefore
             denominator = _sage_const_0 
         else:
             numerator = -numeratorBefore * pi
             denominator = _sage_const_0 
     else:
         displayProblem = "Something went wrong generating a non-Real number."
         print displayProblem
     displayProblem = [numerator, denominator, negOrNo]
     return displayProblem
 
 def generateDisplay(answer):
     if answer == "Natural":
         numerator, denominator, negOrNo = generateNatural()
     elif answer == "Whole":
         numerator, denominator, negOrNo = generateWhole()
     elif answer == "Integer":
         numerator, denominator, negOrNo = generateInteger()
     elif answer == "Rational":
         numerator, denominator, negOrNo = generateRational()
     elif answer == "Irrational":
         numerator, denominator, negOrNo = generateIrrational()
     elif answer == "NotRealNumber":
         numerator, denominator, negOrNo = generateNotReal()
     else:
         numerator, denominator, negOrNo = [_sage_const_0 , _sage_const_0 , _sage_const_0 ]
         print "\n\n\n Something went wrong choosing how to display the problem. \n\n\n\n"
     return [numerator, denominator, negOrNo]
 
 def assignSetValue(set):
     if set == "Natural":
         value = _sage_const_0 
     elif set == "Whole":
         value = _sage_const_1 
     elif set == "Integer":
         value = _sage_const_2 
     elif set == "Rational":
         value = _sage_const_3 
     elif set == "Irrational":
         value = _sage_const_4 
     elif set == "NotRealNumber":
         value = _sage_const_5 
     else:
         value = _sage_const_6 
         print "Something went wrong when assigning the set a value. Please look into this."
     return value
 
 ############ END OF DEFINITIONS ###############
 
 listOptions=["Natural", "Whole", "Integer", "Rational", "Irrational", "NotRealNumber"]
 
 ###### QUESTION 1 #########
 set1 = sample(listOptions, _sage_const_1 )[_sage_const_0 ]
 print set1
 answer1 = assignSetValue(set1)
 numerator1, denominator1, negOrNo1 = generateDisplay(set1)
 
 ###### QUESTION 2 #########
 set2 = sample(listOptions, _sage_const_1 )[_sage_const_0 ]
 answer2 = assignSetValue(set2)
 numerator2, denominator2, negOrNo2 = generateDisplay(set2)
 
 ###### QUESTION 3 #########
 set3 = sample(listOptions, _sage_const_1 )[_sage_const_0 ]
 answer3 = assignSetValue(set3)
 numerator3, denominator3, negOrNo3 = generateDisplay(set3)
 
except:
 _st_.goboom(_sage_const_223 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_228 
 _st_.inline(_sage_const_0 , latex(negOrNo1))
except:
 _st_.goboom(_sage_const_228 )
try:
 _st_.current_tex_line = _sage_const_228 
 _st_.inline(_sage_const_1 , latex(numerator1))
except:
 _st_.goboom(_sage_const_228 )
try:
 _st_.current_tex_line = _sage_const_228 
 _st_.inline(_sage_const_2 , latex(denominator1))
except:
 _st_.goboom(_sage_const_228 )
try:
 _st_.current_tex_line = _sage_const_239 
 _st_.inline(_sage_const_3 , latex(answer1))
except:
 _st_.goboom(_sage_const_239 )
try:
 _st_.current_tex_line = _sage_const_243 
 _st_.inline(_sage_const_4 , latex(negOrNo2))
except:
 _st_.goboom(_sage_const_243 )
try:
 _st_.current_tex_line = _sage_const_243 
 _st_.inline(_sage_const_5 , latex(numerator2))
except:
 _st_.goboom(_sage_const_243 )
try:
 _st_.current_tex_line = _sage_const_243 
 _st_.inline(_sage_const_6 , latex(denominator2))
except:
 _st_.goboom(_sage_const_243 )
try:
 _st_.current_tex_line = _sage_const_254 
 _st_.inline(_sage_const_7 , latex(answer2))
except:
 _st_.goboom(_sage_const_254 )
try:
 _st_.current_tex_line = _sage_const_258 
 _st_.inline(_sage_const_8 , latex(negOrNo3))
except:
 _st_.goboom(_sage_const_258 )
try:
 _st_.current_tex_line = _sage_const_258 
 _st_.inline(_sage_const_9 , latex(numerator3))
except:
 _st_.goboom(_sage_const_258 )
try:
 _st_.current_tex_line = _sage_const_258 
 _st_.inline(_sage_const_10 , latex(denominator3))
except:
 _st_.goboom(_sage_const_258 )
try:
 _st_.current_tex_line = _sage_const_269 
 _st_.inline(_sage_const_11 , latex(answer3))
except:
 _st_.goboom(_sage_const_269 )
_st_.endofdoc()

