## -*- encoding: utf-8 -*-
## This file (graphingQuadratics.sagetex.sage) was *autogenerated* from graphingQuadratics.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('graphingQuadratics', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
